### PR TITLE
Clarify way for dev to test

### PR DESCRIPTION
**Pull request by jgujgu**

### CODE REVIEW

**Comment by cbrunsdon** [comment]
Sorry @jgujgu we have not bee good about watching the extension repos.

I'm a little weirded by the use of lvh.me but I suppose counting on it always resolving to 127 seems reasonable?

:+1:

**Comment by jgujgu** [comment]
I am not to clear on the purpose for its use, but radar suggested it to me when I was clueless.

**Comment by cbrunsdon** [comment]
@jgujgu lvh.me is a domain that resolves the 127.0.0.1 (localhost, your current computer). Additionally it has a wildcard for any subdomain for 127.0.0.1. Its an easy way someone set up to do local development with a real domain structure.

**Comment by adammathys** [comment]
:+1: Definitive improvement and probably one of the easier ways to get up and running. I think I'll start setting up some wiki pages for stuff like this, because there are some relatively simple alternatives that might be worth documenting as well.

**Pull request merged**
