### PR TITLE
Remove StorePaymentMethod functionality

### PR DESCRIPTION
**Pull request by jordan-brough**
It was broken by a Solidus update and we don't know of any actual
production usage of the feature. And it involved monkey-patching
Spree::Order and Spree::PaymentMethod. So we'll just remove it.

See also these associated PRs:

- https://github.com/solidusio/solidus/pull/248#issuecomment-130145406 (where it became broken)
- https://github.com/jordan-brough/solidus/pull/1 (idea for fixing)
- https://github.com/solidusio/solidus_multi_domain/pull/13 (idea for fixing)
- https://github.com/solidusio/solidus_multi_domain/pull/14 (idea for fixing)

### CODE REVIEW

**Comment by magnusvk** [comment]
@gmacdougall added this functionality in https://github.com/solidusio/solidus_multi_domain/commit/03582381c6bdec16465d6f78ee24ba2e1c18b240. Can we really safely remove it? I'm :+1: from the Bonobos point of view but I'm wondering if this is too heavy-handed.

**Comment by jordan-brough** [comment]
Yah I'm definitely waiting for an FRT :+1: on this.  @gmacdougall?

**Comment by jordan-brough** [comment]
@cbrunsdon says they have used this so I've opened https://github.com/solidusio/solidus/pull/309 instead.

**Comment by cbrunsdon** [comment]
Yea, for historical heads up: When we've done multi-tenanted setups with different stores serving different geographical regions, we had different payment methods associated with each store.

**Pull request closed without merging**
