### PR TITLE
Fix for payment environment removal

### PR DESCRIPTION
**Pull request by jordan-brough**
Remove payment_method.environment from Admin::StoresController#index

This was removed from Solidus.

Also, fix issue w/ rendering views in spec/dummy app.

### CODE REVIEW

**Comment by kamui** [comment]
Looks good :horse_racing: :trophy:

**Comment by magnusvk** [comment]
:+1:

**Comment by magnusvk** [comment]
:+1:

**Comment by jordan-brough** [comment]
@gmacdougall @cbrunsdon @jhawthorn can one of you take a look when you have a minute?

**Comment by gmacdougall** [comment]
:+1:

**Pull request merged**
